### ISSUE TITLE
请问如何把这个部署到 cloudflare pages 或者 azure 静态 web 托管？

### ISSUE THREAD

**Issue by ceneax** [Innei/Shiro#108]
### Describe the bug

文档里我看到只有部署到 vercel 的教程，我试了下部署到 cloudflare pages 和 Azure 都报错。

Azure 使用的是 GitHub actions 去构建和部署的，actions 报的错是：
```
Using edge runtime on a page currently disables static generation for that page
DOMException [InvalidCharacterError]: Invalid character
at new DOMException (node:internal/per_context/domexception:53:5)
at _node_internal (node:internal/util:520:10)
at atob (node:buffer:1343:13)
at isomorphicAtob (/github/workspace/.next/server/chunks/9834.js:91:3138)
at isPublishableKey (/github/workspace/.next/server/chunks/9834.js:91:4437)
at Object.parsePublishableKey (/github/workspace/.next/server/chunks/9834.js:91:4138)
at redirect (/github/workspace/.next/server/chunks/9834.js:79:22709)
at 38798 (/github/workspace/.next/server/chunks/9834.js:84:311)
at webpack_require (/github/workspace/.next/server/webpack-runtime.js:1:146)
at 60475 (/github/workspace/.next/server/chunks/1447.js:17:8018)
Build error occurred
Error: Failed to collect page data for /_not-found
at /github/workspace/node_modules/next/dist/build/utils.js:1178:15
at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
type: 'Error'
}
```

由于我对 next.js和前端不太了解，所以想请问下作者，这个要如何部署呢？

### Reproduction

如上

### System Info

```Shell
azure static web page
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Innei** [comment]
咱也不太懂这个
