### ISSUE TITLE
最新版部署到vercel报错

### ISSUE THREAD

**Issue by coderz-w** [Innei/Shiro#161]
### Describe the bug

好像是tailwindcss的问题
[16:22:33.968] Running build in Washington, D.C., USA (East) – iad1 (Hive)
[16:22:34.123] Cloning github.com/coderz-w/Shiro (Branch: main, Commit: 2763bc6)
[16:22:34.604] Previous build cache not available
[16:22:34.629] Cloning completed: 505.588ms
[16:22:35.139] Running "vercel build"
[16:22:36.035] Vercel CLI 32.5.4
[16:22:37.033] Warning: Detected "engines": { "node": ">=18" } in your `package.json` that will automatically upgrade when a new major Node.js Version is released. Learn More: http://vercel.link/node-version
[16:22:37.066] Detected `pnpm-lock.yaml` version 6 generated by pnpm 8
[16:22:37.089] Installing dependencies...
[16:22:37.855] Lockfile is up to date, resolution step is skipped
[16:22:38.001] Progress: resolved 1, reused 0, downloaded 0, added 0
[16:22:38.235] Packages: +895
[16:22:38.236] ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
[16:22:39.003] Progress: resolved 895, reused 0, downloaded 29, added 13
[16:22:40.004] Progress: resolved 895, reused 0, downloaded 87, added 73
[16:22:41.005] Progress: resolved 895, reused 0, downloaded 135, added 124
[16:22:42.006] Progress: resolved 895, reused 0, downloaded 136, added 125
[16:22:43.007] Progress: resolved 895, reused 0, downloaded 155, added 139
[16:22:44.007] Progress: resolved 895, reused 0, downloaded 206, added 192
[16:22:45.007] Progress: resolved 895, reused 0, downloaded 239, added 223
[16:22:46.009] Progress: resolved 895, reused 0, downloaded 333, added 320
[16:22:47.011] Progress: resolved 895, reused 0, downloaded 359, added 343
[16:22:48.013] Progress: resolved 895, reused 0, downloaded 400, added 385
[16:22:49.013] Progress: resolved 895, reused 0, downloaded 500, added 489
[16:22:50.015] Progress: resolved 895, reused 0, downloaded 620, added 609
[16:22:51.015] Progress: resolved 895, reused 0, downloaded 777, added 768
[16:22:52.016] Progress: resolved 895, reused 0, downloaded 850, added 838
[16:22:53.016] Progress: resolved 895, reused 0, downloaded 857, added 850
[16:22:54.022] Progress: resolved 895, reused 0, downloaded 872, added 856
[16:22:54.217] Progress: resolved 895, reused 0, downloaded 895, added 895, done
[16:22:54.596] .../node_modules/simple-git-hooks postinstall$ node ./postinstall.js
[16:22:54.623] .../node_modules/bufferutil install$ node-gyp-build
[16:22:54.624] .../node_modules/utf-8-validate install$ node-gyp-build
[16:22:54.678] .../node_modules/simple-git-hooks postinstall: [INFO] Successfully set the pre-commit with command: pnpm exec lint-staged
[16:22:54.695] .../node_modules/simple-git-hooks postinstall: Done
[16:22:54.825] .../node_modules/bufferutil install: Done
[16:22:54.844] .../node_modules/utf-8-validate install: Done
[16:22:54.853] .../esbuild@0.17.19/node_modules/esbuild postinstall$ node install.js
[16:22:54.931] .../esbuild@0.17.19/node_modules/esbuild postinstall: Done
[16:22:55.435] 
[16:22:55.435] dependencies:
[16:22:55.435] + @clerk/nextjs 4.27.1
[16:22:55.436] + @floating-ui/react-dom 2.0.4
[16:22:55.436] + @mx-space/api-client 1.6.2
[16:22:55.436] + @radix-ui/react-dialog 1.0.5
[16:22:55.436] + @radix-ui/react-select 2.0.0
[16:22:55.436] + @tanstack/query-async-storage-persister 5.8.3
[16:22:55.436] + @tanstack/react-query 5.8.3
[16:22:55.436] + @tanstack/react-query-devtools 5.8.3
[16:22:55.436] + @tanstack/react-query-persist-client 5.8.3
[16:22:55.436] + @vercel/analytics 1.1.1
[16:22:55.436] + @vercel/postgres 0.5.1
[16:22:55.436] + axios 1.6.1
[16:22:55.436] + bypass-vue-devtools 0.0.6
[16:22:55.436] + clsx 2.0.0
[16:22:55.437] + daisyui 4.0.4
[16:22:55.437] + dayjs 1.11.10
[16:22:55.437] + emoji-mart 5.5.2
[16:22:55.437] + emoji-picker-react 4.5.15
[16:22:55.437] + foxact 0.2.26
[16:22:55.437] + framer-motion 10.16.4
[16:22:55.437] + idb-keyval 6.2.1
[16:22:55.437] + immer 10.0.3
[16:22:55.437] + jojoo 0.1.1
[16:22:55.437] + jotai 2.5.1
[16:22:55.437] + js-cookie 3.0.5
[16:22:55.437] + markdown-to-jsx <- @innei/markdown-to-jsx 7.2.1-beta.0
[16:22:55.437] + medium-zoom 1.0.8
[16:22:55.437] + mermaid 10.6.1
[16:22:55.437] + next 14.0.2
[16:22:55.438] + next-themes 0.2.1
[16:22:55.441] + openai 4.17.5
[16:22:55.441] + qrcode.react 3.1.0
[16:22:55.441] + react 18.2.0
[16:22:55.441] + react-dom 18.2.0
[16:22:55.441] + react-error-boundary 4.0.11
[16:22:55.441] + react-intersection-observer 9.5.3
[16:22:55.441] + react-toastify 9.1.3
[16:22:55.441] + react-tweet 3.1.1
[16:22:55.441] + react-wrap-balancer 1.1.0
[16:22:55.442] + remove-markdown 0.5.0
[16:22:55.442] + socket.io-client 4.7.2
[16:22:55.442] + tailwind-merge 2.0.0
[16:22:55.442] + uniqolor 1.1.0
[16:22:55.442] + vaul 0.7.9
[16:22:55.442] + xss 1.0.14
[16:22:55.442] 
[16:22:55.443] devDependencies:
[16:22:55.443] + @iconify-json/material-symbols 1.1.62
[16:22:55.444] + @iconify-json/mingcute 1.1.11
[16:22:55.444] + @iconify/tailwind 0.1.3
[16:22:55.444] + @innei/eslint-config-react-ts 0.11.1
[16:22:55.444] + @innei/prettier 0.11.1
[16:22:55.444] + @next/bundle-analyzer 14.0.2
[16:22:55.444] + @tailwindcss/typography 0.5.10
[16:22:55.444] + @types/js-cookie 3.0.6
[16:22:55.444] + @types/markdown-escape 1.1.3
[16:22:55.445] + @types/node 20.9.0
[16:22:55.445] + @types/react 18.2.37
[16:22:55.445] + @types/react-dom 18.2.15
[16:22:55.445] + @types/remove-markdown 0.3.4
[16:22:55.445] + autoprefixer 10.4.16
[16:22:55.445] + cross-env 7.0.3
[16:22:55.445] + dotenv 16.3.1
[16:22:55.445] + eslint 8.53.0
[16:22:55.445] + husky 8.0.3
[16:22:55.445] + lint-staged 15.1.0
[16:22:55.445] + postcss 8.4.31
[16:22:55.445] + postcss-import 15.1.0
[16:22:55.445] + postcss-nested 6.0.1
[16:22:55.445] + postcss-preset-env 9.3.0
[16:22:55.445] + postcss-prune-var 1.1.1
[16:22:55.446] + prettier 3.1.0
[16:22:55.446] + rimraf 5.0.5
[16:22:55.446] + simple-git-hooks 2.9.0
[16:22:55.446] + tailwind-scrollbar 3.0.5
[16:22:55.446] + tailwind-variants 0.1.18
[16:22:55.446] + tailwindcss 3.3.5
[16:22:55.446] + typescript 5.2.2
[16:22:55.446] + typewind 0.1.4
[16:22:55.446] + zx 7.2.3
[16:22:55.446] 
[16:22:55.473] 
[16:22:55.474] > Shiro@0.2.0 prepare /vercel/path0
[16:22:55.474] > pnpm exec simple-git-hooks && test -f .env || cp .env.template .env
[16:22:55.474] 
[16:22:56.168] [INFO] Successfully set the pre-commit with command: pnpm exec lint-staged
[16:22:56.169] [INFO] Successfully set all git hooks
[16:22:56.187] Done in 19s
[16:22:56.226] Detected Next.js version: 14.0.2
[16:22:56.321] Running "pnpm run build"
[16:22:56.912] 
[16:22:56.912] > Shiro@0.2.0 build /vercel/path0
[16:22:56.912] > cross-env NODE_ENV=production next build
[16:22:56.912] 
[16:22:57.848] Attention: Next.js now collects completely anonymous telemetry regarding usage.
[16:22:57.849] This information is used to shape Next.js' roadmap and prioritize features.
[16:22:57.849] You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
[16:22:57.849] https://nextjs.org/telemetry
[16:22:57.850] 
[16:22:57.957]    ▲ Next.js 14.0.2
[16:22:57.957]    - Environments: .env
[16:22:57.957]    - Experiments (use at your own risk):
[16:22:57.957]      · useDeploymentId
[16:22:57.957]      · useDeploymentIdServerActions
[16:22:57.957] 
[16:22:57.958]    Creating an optimized production build ...
[16:23:04.682] 
[16:23:04.683] [1m[33mwarn[39m[22m - As of Tailwind CSS v2.2, `lightBlue` has been renamed to `sky`.
[16:23:04.683] [1m[33mwarn[39m[22m - Update your configuration file to silence this warning.
[16:23:04.684] 
[16:23:04.684] [1m[33mwarn[39m[22m - As of Tailwind CSS v3.0, `warmGray` has been renamed to `stone`.
[16:23:04.684] [1m[33mwarn[39m[22m - Update your configuration file to silence this warning.
[16:23:04.684] 
[16:23:04.685] [1m[33mwarn[39m[22m - As of Tailwind CSS v3.0, `trueGray` has been renamed to `neutral`.
[16:23:04.685] [1m[33mwarn[39m[22m - Update your configuration file to silence this warning.
[16:23:04.685] 
[16:23:04.685] [1m[33mwarn[39m[22m - As of Tailwind CSS v3.0, `coolGray` has been renamed to `gray`.
[16:23:04.685] [1m[33mwarn[39m[22m - Update your configuration file to silence this warning.
[16:23:04.685] 
[16:23:04.686] [1m[33mwarn[39m[22m - As of Tailwind CSS v3.0, `blueGray` has been renamed to `slate`.
[16:23:04.686] [1m[33mwarn[39m[22m - Update your configuration file to silence this warning.
[16:23:50.787] 
[16:23:50.787] [1m[33mwarn[39m[22m - As of Tailwind CSS v2.2, `lightBlue` has been renamed to `sky`.
[16:23:50.788] [1m[33mwarn[39m[22m - Update your configuration file to silence this warning.
[16:23:50.788] 
[16:23:50.788] [1m[33mwarn[39m[22m - As of Tailwind CSS v3.0, `warmGray` has been renamed to `stone`.
[16:23:50.788] [1m[33mwarn[39m[22m - Update your configuration file to silence this warning.
[16:23:50.788] 
[16:23:50.788] [1m[33mwarn[39m[22m - As of Tailwind CSS v3.0, `trueGray` has been renamed to `neutral`.
[16:23:50.789] [1m[33mwarn[39m[22m - Update your configuration file to silence this warning.
[16:23:50.789] 
[16:23:50.789] [1m[33mwarn[39m[22m - As of Tailwind CSS v3.0, `coolGray` has been renamed to `gray`.
[16:23:50.789] [1m[33mwarn[39m[22m - Update your configuration file to silence this warning.
[16:23:50.789] 
[16:23:50.790] [1m[33mwarn[39m[22m - As of Tailwind CSS v3.0, `blueGray` has been renamed to `slate`.
[16:23:50.790] [1m[33mwarn[39m[22m - Update your configuration file to silence this warning.
[16:24:21.207] <w> [webpack.cache.PackFileCacheStrategy] Skipped not serializable cache item 'Compilation/modules|/vercel/path0/node_modules/.pnpm/next@14.0.2_@babel+core@7.23.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[12].oneOf[12].use[2]!/vercel/path0/node_modules/.pnpm/next@14.0.2_@babel+core@7.23.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[12].oneOf[12].use[3]!/vercel/path0/src/styles/index.css': No serializer registered for PostCSSSyntaxError
[16:24:21.209] <w> while serializing webpack/lib/cache/PackFileCacheStrategy.PackContentItems -> webpack/lib/NormalModule -> webpack/lib/ModuleBuildError -> PostCSSSyntaxError
[16:24:24.573] Failed to compile.
[16:24:24.573] 
[16:24:24.573] ./src/styles/index.css:51:5
[16:24:24.573] Syntax error: /vercel/path0/src/styles/clerk.css The `bg-accent-focus` class does not exist. If `bg-accent-focus` is a custom class, make sure it is defined within a `@layer` directive.
[16:24:24.573] 
[16:24:24.573]  [90m 49 | [39m
[16:24:24.573]  [90m 50 | [39m  &[33m:[39mhover [33m{[39m
[16:24:24.574] [1m[31m>[39m[22m[90m 51 | [39m    [36m@apply[39m bg-accent-focus[33m;[39m
[16:24:24.574]  [90m    | [39m    [1m[31m^[39m[22m
[16:24:24.574]  [90m 52 | [39m  [33m}[39m
[16:24:24.574]  [90m 53 | [39m[33m}[39m
[16:24:24.574] 
[16:24:24.574] ./src/styles/index.css
[16:24:24.574] Syntax error: /vercel/path0/src/styles/clerk.css The `bg-accent-focus` class does not exist. If `bg-accent-focus` is a custom class, make sure it is defined within a `@layer` directive. (51:5)
[16:24:24.574] 
[16:24:24.574]  [90m 49 | [39m
[16:24:24.574]  [90m 50 | [39m  &[33m:[39mhover [33m{[39m
[16:24:24.574] [1m[31m>[39m[22m[90m 51 | [39m    [36m@apply[39m bg-accent-focus[33m;[39m
[16:24:24.575]  [90m    | [39m    [1m[31m^[39m[22m
[16:24:24.575]  [90m 52 | [39m  [33m}[39m
[16:24:24.575]  [90m 53 | [39m[33m}[39m
[16:24:24.575] 
[16:24:24.575]     at tryRunOrWebpackError (/vercel/path0/node_modules/.pnpm/next@14.0.2_@babel+core@7.23.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/webpack/bundle5.js:28:311563)
[16:24:24.575]     at __webpack_require_module__ (/vercel/path0/node_modules/.pnpm/next@14.0.2_@babel+core@7.23.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/webpack/bundle5.js:28:131195)
[16:24:24.575]     at __nested_webpack_require_153754__ (/vercel/path0/node_modules/.pnpm/next@14.0.2_@babel+core@7.23.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/webpack/bundle5.js:28:130634)
[16:24:24.575]     at /vercel/path0/node_modules/.pnpm/next@14.0.2_@babel+core@7.23.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/webpack/bundle5.js:28:131487
[16:24:24.575]     at symbolIterator (/vercel/path0/node_modules/.pnpm/next@14.0.2_@babel+core@7.23.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/neo-async/async.js:1:14444)
[16:24:24.575]     at done (/vercel/path0/node_modules/.pnpm/next@14.0.2_@babel+core@7.23.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/neo-async/async.js:1:14824)
[16:24:24.576]     at Hook.eval [as callAsync] (eval at create (/vercel/path0/node_modules/.pnpm/next@14.0.2_@babel+core@7.23.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/webpack/bundle5.js:13:28867), <anonymous>:15:1)
[16:24:24.576]     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/vercel/path0/node_modules/.pnpm/next@14.0.2_@babel+core@7.23.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/webpack/bundle5.js:13:26021)
[16:24:24.576]     at /vercel/path0/node_modules/.pnpm/next@14.0.2_@babel+core@7.23.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/webpack/bundle5.js:28:130354
[16:24:24.576]     at symbolIterator (/vercel/path0/node_modules/.pnpm/next@14.0.2_@babel+core@7.23.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/neo-async/async.js:1:14402)
[16:24:24.576] -- inner error --
[16:24:24.576] Syntax error: /vercel/path0/src/styles/clerk.css The `bg-accent-focus` class does not exist. If `bg-accent-focus` is a custom class, make sure it is defined within a `@layer` directive. (51:5)
[16:24:24.576] 
[16:24:24.576]  [90m 49 | [39m
[16:24:24.576]  [90m 50 | [39m  &[33m:[39mhover [33m{[39m
[16:24:24.576] [1m[31m>[39m[22m[90m 51 | [39m    [36m@apply[39m bg-accent-focus[33m;[39m
[16:24:24.576]  [90m    | [39m    [1m[31m^[39m[22m
[16:24:24.576]  [90m 52 | [39m  [33m}[39m
[16:24:24.577]  [90m 53 | [39m[33m}[39m
[16:24:24.577] 
[16:24:24.577]     at Object.<anonymous> (/vercel/path0/node_modules/.pnpm/next@14.0.2_@babel+core@7.23.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[12].oneOf[12].use[2]!/vercel/path0/node_modules/.pnpm/next@14.0.2_@babel+core@7.23.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[12].oneOf[12].use[3]!/vercel/path0/src/styles/index.css:1:7)
[16:24:24.577]     at /vercel/path0/node_modules/.pnpm/next@14.0.2_@babel+core@7.23.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/webpack/bundle5.js:28:915116
[16:24:24.577]     at Hook.eval [as call] (eval at create (/vercel/path0/node_modules/.pnpm/next@14.0.2_@babel+core@7.23.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/webpack/bundle5.js:13:28645), <anonymous>:7:1)
[16:24:24.577]     at Hook.CALL_DELEGATE [as _call] (/vercel/path0/node_modules/.pnpm/next@14.0.2_@babel+core@7.23.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/webpack/bundle5.js:13:25915)
[16:24:24.577]     at /vercel/path0/node_modules/.pnpm/next@14.0.2_@babel+core@7.23.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/webpack/bundle5.js:28:131228
[16:24:24.577]     at tryRunOrWebpackError (/vercel/path0/node_modules/.pnpm/next@14.0.2_@babel+core@7.23.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/webpack/bundle5.js:28:311517)
[16:24:24.577]     at __webpack_require_module__ (/vercel/path0/node_modules/.pnpm/next@14.0.2_@babel+core@7.23.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/webpack/bundle5.js:28:131195)
[16:24:24.577]     at __nested_webpack_require_153754__ (/vercel/path0/node_modules/.pnpm/next@14.0.2_@babel+core@7.23.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/webpack/bundle5.js:28:130634)
[16:24:24.577]     at /vercel/path0/node_modules/.pnpm/next@14.0.2_@babel+core@7.23.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/webpack/bundle5.js:28:131487
[16:24:24.577]     at symbolIterator (/vercel/path0/node_modules/.pnpm/next@14.0.2_@babel+core@7.23.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/neo-async/async.js:1:14444)
[16:24:24.578] 
[16:24:24.578] Generated code for /vercel/path0/node_modules/.pnpm/next@14.0.2_@babel+core@7.23.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[12].oneOf[12].use[2]!/vercel/path0/node_modules/.pnpm/next@14.0.2_@babel+core@7.23.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[12].oneOf[12].use[3]!/vercel/path0/src/styles/index.css
[16:24:24.578] 
[16:24:24.578] Import trace for requested module:
[16:24:24.578] ./src/styles/index.css
[16:24:24.578] 
[16:24:24.588] 
[16:24:24.588] > Build failed because of webpack errors
[16:24:24.607]  ELIFECYCLE  Command failed with exit code 1.
[16:24:24.631] Error: Command "pnpm run build" exited with 1
[16:24:25.856] 

### Reproduction

使用最新版的 shiro，并 fork 到自己的 GitHub，然后用 vercel 直接部署

### System Info

```Shell
vercel
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Innei** [comment]
Fixed in the latest version

**Comment by coderz-w** [comment]
> 在最新版本中修复

可以问一下是出了什么问题吗
