### ISSUE TITLE
使用vercel作为前端绑定域名后，rss链接如何设置？

### ISSUE THREAD

**Issue by whitewatercn** [Innei/Shiro#425]
### Describe the bug

主机运行后端，vercel运行前端shiro

主机上[参考反向代理教程](https://mx-space.js.org/docs/extra#%E5%8F%8D%E5%90%91%E4%BB%A3%E7%90%86)用1panel配置了单域名 myblog.whitewater.wang（dns解析到主机），并配置反向代理（具体配置见下），另外在vercel绑定域名blog.whitewater.wang（dns解析到vercel）
现在前后端均可正常访问

myblog.whitewater.wang/feed 可以正常使用，但在站点blog.whitewater.wang 上点击订阅rss，会自动跳转到blog.whitewater.wang/feed ，这是一个无法访问的链接，请问接下来如何设置？

# 演示
<img width="911" alt="image" src="https://github.com/user-attachments/assets/4608e9d2-9f8d-47e1-851c-5ca70d23e110">

https://github.com/user-attachments/assets/41a8178c-68cc-455d-8537-1e15790bf96e

# 反向代理设置
```

server {
    listen 80;
    listen 443 ssl http2 ; 
    ## 绑定域名 
    server_name myblog.whitewater.wang; 
    index index.html; 
    proxy_set_header Host $host; 
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
    proxy_set_header X-Forwarded-Host $server_name; 
    proxy_set_header Upgrade $http_upgrade; 
    proxy_set_header Connection "upgrade"; 
    error_log /www/sites/myblog.whitewater.wang/log/error.log;
    access_log /www/sites/myblog.whitewater.wang/log/access.log; 
    location /socket.io {
        proxy_set_header Upgrade $http_upgrade; 
        proxy_set_header Connection "Upgrade"; 
        proxy_set_header Host $host; 
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
        proxy_set_header X-Forwarded-Proto $scheme; 
        proxy_pass http://127.0.0.1:2333/socket.io; 
    }
    location /api/v2 {
        proxy_pass http://127.0.0.1:2333/api/v2; 
    }
    location /render {
        proxy_pass http://127.0.0.1:2333/render; 
    }
    location / {
        proxy_pass http://127.0.0.1:2323; 
    }
    location /qaqdmin {
        proxy_pass http://127.0.0.1:2333/proxy/qaqdmin;
    }
    location /proxy {
        proxy_pass http://127.0.0.1:2333/proxy;
    }
 
    location ~* \/(feed|sitemap|atom.xml) {
        proxy_pass http://127.0.0.1:2333/$1; 
    }
    ssl_certificate /www/sites/myblog.whitewater.wang/ssl/fullchain.pem; 
    ssl_certificate_key /www/sites/myblog.whitewater.wang/ssl/privkey.pem; 
    ssl_protocols TLSv1.3 TLSv1.2 TLSv1.1 TLSv1; 
    ssl_ciphers 'ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!3DES:!MD5:!PSK'; 
    ssl_prefer_server_ciphers on; 
    ssl_session_cache shared:SSL:10m; 
    ssl_session_timeout 10m; 
    error_page 497 https://$host$request_uri; 
    limit_conn perserver 300; 
    limit_conn perip 25; 
    limit_rate 512k; 
}
```
# 后端相关设置
<img width="1124" alt="image" src="https://github.com/user-attachments/assets/abc8281e-36d1-4e7d-a7d3-209724e5275e">

# vercel相关设置
<img width="1262" alt="image" src="https://github.com/user-attachments/assets/ad2bf936-ed03-4eff-9a4b-79688ef7aaa3">

# vercel报错
是这个报错吗？
<img width="1439" alt="image" src="https://github.com/user-attachments/assets/5a5b754b-d32e-4b44-ae4e-418d51718675">

```
⨯ SyntaxError: Unexpected token '<', "<rss xmlns"... is not valid JSON
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (node:internal/deps/undici/undici:4306:19)
    at successSteps (node:internal/deps/undici/undici:4288:27)
    at fullyReadBody (node:internal/deps/undici/undici:2724:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async consumeBody (node:internal/deps/undici/undici:4297:7)
    at async Promise.all (index 0)
    at async eB (/var/task/.next/server/app/feed/route.js:1:25383)
    at async /var/task/node_modules/.pnpm/next@14.2.5_@babel+core@7.24.6_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:36258
    at async eR.execute (/var/task/node_modules/.pnpm/next@14.2.5_@babel+core@7.24.6_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:26874)
```

### Reproduction

-

### System Info

```Shell
使用vercel部署shiro，并没有使用npx
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Innei** [comment]
你的 nginx 配置有问题。`http://myblog.whitewater.wang/api/v2/aggregate/feed` 这个应该是 json 而不是 xml。

**Comment by Innei** [comment]
把 

```
location ~* \/(feed|sitemap|atom.xml) {
        proxy_pass http://127.0.0.1:2333/$1; 
    }
```

删了 试试

**Comment by whitewatercn** [comment]
> 把
> 
> ```
> location ~* \/(feed|sitemap|atom.xml) {
>         proxy_pass http://127.0.0.1:2333/$1; 
>     }
> ```
> 
> 删了 试试

已经删除，重新部署了vercel，在访客模式下访问，还是会直接跳到blog.whitewater.wang/feed，无法访问
```

server {
    listen 80;
    listen 443 ssl http2 ; 
    ## 绑定域名 
    server_name myblog.whitewater.wang; 
    index index.html; 
    proxy_set_header Host $host; 
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
    proxy_set_header X-Forwarded-Host $server_name; 
    proxy_set_header Upgrade $http_upgrade; 
    proxy_set_header Connection "upgrade"; 
    error_log /www/sites/myblog.whitewater.wang/log/error.log;
    access_log /www/sites/myblog.whitewater.wang/log/access.log; 
    location /socket.io {
        proxy_set_header Upgrade $http_upgrade; 
        proxy_set_header Connection "Upgrade"; 
        proxy_set_header Host $host; 
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
        proxy_set_header X-Forwarded-Proto $scheme; 
        proxy_pass http://127.0.0.1:2333/socket.io; 
    }
    location /api/v2 {
        proxy_pass http://127.0.0.1:2333/api/v2; 
    }
    location /render {
        proxy_pass http://127.0.0.1:2333/render; 
    }
    location / {
        proxy_pass http://127.0.0.1:2323; 
    }
    location /qaqdmin {
        proxy_pass http://127.0.0.1:2333/proxy/qaqdmin;
    }
    location /proxy {
        proxy_pass http://127.0.0.1:2333/proxy;
    }

    ssl_certificate /www/sites/myblog.whitewater.wang/ssl/fullchain.pem; 
    ssl_certificate_key /www/sites/myblog.whitewater.wang/ssl/privkey.pem; 
    ssl_protocols TLSv1.3 TLSv1.2 TLSv1.1 TLSv1; 
    ssl_ciphers 'ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!3DES:!MD5:!PSK'; 
    ssl_prefer_server_ciphers on; 
    ssl_session_cache shared:SSL:10m; 
    ssl_session_timeout 10m; 
    error_page 497 https://$host$request_uri; 
    limit_conn perserver 300; 
    limit_conn perip 25; 
    limit_rate 512k; 
}
```

**Comment by IshuaWang** [comment]
@whitewatercn 问个问题啊，你这个不是设置成单域名吗？为什么还要用两个域名呢？
