### ISSUE TITLE
获取TMDB数据超时

### ISSUE THREAD

**Issue by liyown** [Innei/Shiro#437]
### Describe the bug

设置好API KEY后前端请求https://me.liuyaowen.club/api/tmdb/movie/1299537?language=zh-CN超时，后台日志输出：
 ⨯ Error: fetch failed
    at context.fetch (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.6_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/web/sandbox/context.js:292:38)
    at i (/app/.next/server/edge-chunks/219.js:6:45698)
    at U (/app/.next/server/edge-chunks/219.js:6:77216)
    at /app/.next/server/edge-chunks/219.js:6:79437
    at /app/.next/server/edge-chunks/219.js:6:85367
    at a.with (/app/.next/server/edge-chunks/219.js:1:11313)
    at l.with (/app/.next/server/edge-chunks/219.js:1:5513)
    at l.startActiveSpan (/app/.next/server/edge-chunks/219.js:1:20565)
    at a.startActiveSpan (/app/.next/server/edge-chunks/219.js:1:21099)
    at /app/.next/server/edge-chunks/219.js:6:84914 {
  cause: ConnectTimeoutError: Connect Timeout Error
      at onConnectTimeout (eval at requireWithFakeGlobalScope (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.6_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/edge-runtime/index.js:1:657096), <anonymous>:9145:28)
      at eval (eval at requireWithFakeGlobalScope (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.6_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/edge-runtime/index.js:1:657096), <anonymous>:9101:50)
      at Immediate.eval [as _onImmediate] (eval at requireWithFakeGlobalScope (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.24.6_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/edge-runtime/index.js:1:657096), <anonymous>:9133:13)
      at process.processImmediate (node:internal/timers:476:21)
      at process.callbackTrampoline (node:internal/async_hooks:128:17) {
    code: 'UND_ERR_CONNECT_TIMEOUT'
  }

### Reproduction

None

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by liyown** [comment]
emmmm，我好像发现问题了，ping api.themoviedb.org在没有代理的情况下是ping不通的，我部署在国内服务器，应该也是无法访问的吧。。。请问有什么办法解决吗

**Comment by liyown** [comment]
提供方案：https://me.liuyaowen.club/dashboard/notes/edit?id=66c4a2db4b2aebd1675403f3

**Comment by Innei** [comment]
服务器网络问题，请自行解决。
